services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: product_catalog_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product_catalog
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - product_catalog_network

  # Laravel API Backend
  laravel-api:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: product_catalog_api
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=product_catalog
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravelpassword
    volumes:
      - ./laravel-api:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - product_catalog_network
    # command: sh -c "composer install && php artisan key:generate && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=8000"

  # Vue Frontend
  vue-frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    container_name: product_catalog_frontend
    volumes:
      - ./vue-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - product_catalog_network
    # command: npm run dev

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: product_catalog_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-api
      - vue-frontend
    networks:
      - product_catalog_network

volumes:
  db_data:

networks:
  product_catalog_network:
    driver: bridge